development:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUD_KEY"] %>
  api_secret: <%= ENV["CLOUD_SECRET"] %>
  enhance_image_tag: false
  static_image_support: false
production:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUD_KEY"] %>
  api_secret: <%= ENV["CLOUD_SECRET"] %>
  enhance_image_tag: false
  static_image_support: false
test:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUD_KEY"] %>
  api_secret: <%= ENV["CLOUD_SECRET"] %>
  enhance_image_tag: false
  static_image_support: false
